on:
  pull_request:
    branches:
      - "master"

jobs:
  ghcoin-transaction:
    runs-on: ubuntu-latest
    name: Process ghcoin transactions
    steps:
      - name: Validate transaction
        id: hello
        uses: plamorg/ghcoin@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge pull request
        id: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "ghcoin: process transaction {pullRequest.number}"
          MERGE_LABELS: ""

