on:
  pull_request:
    branches:
      - "master"

jobs:
  ghcoin-transaction:
    runs-on: ubuntu-latest
    name: Process ghcoin transactions
    steps:
      - name: Validate transaction
        id: hello
        uses: plamorg/ghcoin@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

