on:
  pull_request:
    types:
      - opened
    branches:    
      - 'master'

jobs:
  ghcoin-transaction:
    runs-on: ubuntu-latest
    name: Process ghcoin transactions
    steps:
      - name: Validate transaction
        id: hello
        uses: plamorg/ghcoin@v1
        with:
          total-amount: '1000'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
